using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CF_Server
{
    public class Enums
    {
        public enum AccountState : byte
        {
            Default = 0,
            Banned = 1,
            GameMaster = 100,
        }
        public enum ServerType : ushort
        {
            Normal = 1,
            Clan
        }
        public enum LoginTypes : byte
        {
            NoError,
            UnknownError,
            Player_Already_Logged_In,
            Connection_Expired,
            Unknown_Username_Or_Password,
            Could_not_connect_to_the_Server,
            Welcome_By_Crossfire,
            You_Cannot_Access_The_Test_Server,
            You_Dont_Have_The_Lastest_Version_of_Crossfire,
            You_Cannot_Join_The_Game_For_5_Minutes,
            Unknown,
            Blocked,
        }
        public enum RoomWeapons : byte
        {
            AllWeapons,
            Knife,
            Pistol,
            Sniper
        }
        public enum RoomAnswer : byte
        {
            Success,
            Full,
            Unknown,
            WrongPassword
        }
        public enum RoomObjType : byte
        {
            Rounds,
            Kills,
            Time,
            Escape_Mode_Attack_and_Defense,
            Zombie_Mode_Easy = 5,
            Zombie_Mode_Normal,
            Zombie_Mode_Hard,
            Zombie_Mode_Expert,
            Zombie_Mode_Nightmare,
            Shadow_EM = 11,
            Shadow_INF,
            Score,
            Single_Round,
        }
        public enum RoomStatus : byte
        {
            inGame_CantJoin,
            Waiting,
            inGame
        }
        public enum GameMode : byte
        {
            Search_and_Destroy = 1,
            Team_Death_Match,
            Shadow_Mode,
            Ghost_Mode,
            Elimination,
            Free_For_All,
            Weapon_Master = 36,
            Escape_Mode,
            Wave,
            Super_Soldier_TD,
            Super_Soldier_S_and_D,
            Supression_Mode,
            Spy_Mode,
            Captain_Mode,
            Bombing_Mode,
            Team_Escape_Mode
        }
        public enum Grades : byte
        {
            //Soldiers: count = 9;
            Trainee_1 = 0,

            Trainee_2 = 1,
            Private = 2,
            PFC = 3,
            Corporal = 4,
            Sergeant_1 = 5,
            Sergeant_2 = 6,
            Sergeant_3 = 7,
            Sergeant_4 = 8,

            //Petty Officers: count = 18;
            Staff_Sergeant_1 = 9,

            Staff_Sergeant_2 = 10,
            Staff_Sergeant_3 = 11,
            Staff_Sergeant_4 = 12,
            Staff_Sergeant_5 = 13,
            Staff_Sergeant_6 = 14,
            SFC_1 = 15,
            SFC_2 = 16,
            SFC_3 = 17,
            SFC_4 = 18,
            SFC_5 = 19,
            SFC_6 = 20,
            Master_Sergeant_1 = 21,
            Master_Sergeant_2 = 22,
            Master_Sergeant_3 = 23,
            Master_Sergeant_4 = 24,
            Master_Sergeant_5 = 25,
            Master_Sergeant_6 = 26,

            //Company Officers: count = 25;
            Second_Lieutenant_1 = 27,

            Second_Lieutenant_2 = 28,
            Second_Lieutenant_3 = 29,
            Second_Lieutenant_4 = 30,
            Second_Lieutenant_5 = 31,
            Second_Lieutenant_6 = 32,
            Second_Lieutenant_7 = 33,
            Second_Lieutenant_8 = 34,
            First_Lieutenant_1 = 35,
            First_Lieutenant_2 = 36,
            First_Lieutenant_3 = 37,
            First_Lieutenant_4 = 38,
            First_Lieutenant_5 = 39,
            First_Lieutenant_6 = 40,
            First_Lieutenant_7 = 41,
            First_Lieutenant_8 = 42,
            Captain_1 = 43,
            Captain_2 = 44,
            Captain_3 = 45,
            Captain_4 = 46,
            Captain_5 = 47,
            Captain_6 = 48,
            Captain_7 = 49,
            Captain_8 = 50,

            //Field Officers: count = 23;
            Major_1 = 51,

            Major_2 = 52,
            Major_3 = 53,
            Major_4 = 54,
            Major_5 = 55,
            Major_6 = 56,
            Major_7 = 57,
            Major_8 = 58,
            Lieutenant_Colonel_1 = 59,
            Lieutenant_Colonel_2 = 60,
            Lieutenant_Colonel_3 = 61,
            Lieutenant_Colonel_4 = 62,
            Lieutenant_Colonel_5 = 63,
            Lieutenant_Colonel_6 = 64,
            Lieutenant_Colonel_7 = 65,
            Lieutenant_Colonel_8 = 66,
            Colonel_1 = 67,
            Colonel_2 = 68,
            Colonel_3 = 69,
            Colonel_4 = 70,
            Colonel_5 = 71,
            Colonel_6 = 72,
            Colonel_7 = 73,
            Colonel_8 = 74,

            //Generals:count = 25;
            Brigadier_General_1 = 75,

            Brigadier_General_2 = 76,
            Brigadier_General_3 = 77,
            Brigadier_General_4 = 78,
            Brigadier_General_5 = 79,
            Brigadier_General_6 = 80,
            Major_General_1 = 81,
            Major_General_2 = 82,
            Major_General_3 = 83,
            Major_General_4 = 84,
            Major_General_5 = 85,
            Major_General_6 = 86,
            Lieutenant_General_1 = 87,
            Lieutenant_General_2 = 88,
            Lieutenant_General_3 = 89,
            Lieutenant_General_4 = 90,
            Lieutenant_General_5 = 91,
            Lieutenant_General_6 = 92,
            General_1 = 93,
            General_2 = 94,
            General_3 = 95,
            General_4 = 96,
            General_5 = 97,
            General_6 = 98,
            Marshall = 99
        }
        public enum ItemsModel
        {
            Weapon,//C
            CharacterEquipment,//B
            Character,//A
            Item,//I
            Bag//D
        }
        public enum Items : ushort
        {
            BL_Logo = 20,
            GR_Logo = 21,
            Cross_Fire_Logo = 22,
            Channel_Megaphone = 23,
            Server_Megaphone = 24,
            BL_Sign = 25,
            GR_Sign = 26,
            BL_Crouch = 27,
            GR_Crouch = 28,
            C4 = 29,
            Black_List = 30,
            Global_Risk = 31,
            Volcano = 32,
            Hot_Blooded_Merc = 33,
            ULP_RP_Capsule = 34,
            Bulletproof_Vest = 35,
            Bulletproof_Helmet = 36,
            Blue_Muzzle_Flash = 37,
            Extra_Grenades = 38,
            C4_Kit = 39,
            Jump_Boots = 40,
            Mutant_Hook = 41,
            Mutation_Mode_Mag = 42,
            Mutant_Fire_Suit = 43,
            Reduce_Stun_and_knockback = 44,
            Mutant_Hulk = 45,
            Crazy_Mutant = 46,
            Ink_Mutant = 47,
            Headshot = 48,
            Multi_Kill = 49,
            Bubble = 50,
            Bubble_2 = 51,
            Circle = 52,
            Capsule_Coupon = 53,
            Sniper = 54,
            Stormer = 55,
            Scout = 56,
            Special_Ops = 57,
            Founder = 58,
            Frontier = 59,
            EXP_Plus_50 = 5,
            _2011_Halloween_RP_Capsule = 60,
            GR_Fire = 61,
            BL_Fire = 62,
            _2011_Christmas_RP_Capsule = 63,
            Fox_Howl_RP_Capsule_ = 64,
            Mutant_Assassin = 69,
            Holly_Green = 70,
            Red_Ribbon = 71,
            Silent_Snowman = 72,
            Merry_Snowman = 73,
            Killer_Snowman = 74,
            Christmas_Tree = 75,
            Holly_Green_2 = 76,
            Red_Ribbon_2 = 77,
            _2012_New_year = 78,
            Albania = 79,
            Andorra = 80,
            Austria = 81,
            Belgium = 82,
            Bosnia_and_Herzegovina = 83,
            Bulgaria = 84,
            Croatia = 85,
            Czech_Republic = 86,
            Denmark = 87,
            European_Union = 88,
            Finland = 89,
            Greece = 90,
            Hungary = 91,
            Iceland = 92,
            Ireland = 93,
            Luxembourg = 94,
            Macedonia = 95,
            Malta = 96,
            Monaco = 97,
            Montenegro = 98,
            Norway = 99,
            Poland = 100,
            Romania = 101,
            San_Marino = 102,
            Serbia = 103,
            Slovakia = 104,
            Slovenia = 105,
            Swaziland = 106,
            Sweden = 107,
            Vatican_City = 108,
            Argentina = 109,
            Spain = 110,
            Netherlands = 111,
            Germany = 112,
            Italy = 113,
            Brazil = 114,
            France = 115,
            Portugal = 116,
            South_Africa = 117,
            England = 118,
            South_Korea = 119,
            USA = 120,
            Japan = 121,
            Vietnam = 122,
            Crystal_Box = 123,
            Gold_Box = 124,
            Silver_Box = 125,
            Bronze_Box = 126,
            Green_Muzzle_Flash = 127,
            Swarm = 128,
            Infected = 129,
            Quarantine = 130,
            Outbreak = 131,
            Heraclops_Box = 132,
            Chaos_Box = 133,
            HypoMed_Gun_S = 134,
            HypoMed_Gun_L = 135,
            Respawn_Token = 136,
            M14EBR_RP_Capsule = 137,
            RPK_Gold_RP_Capsule = 138,
            MOS_RP_Capsule = 139,
            Heraclops = 140,
            Ghost = 141,
            Flame = 142,
            Boss_Chaos = 143,
            Boss_Chaos_2 = 144,
            Boss_Heraclops = 145,
            Boss_Heraclops_2 = 146,
            M4A1_Custom_RP_Capsule = 147,
            M37_Stakeout_RP_Capsule = 148,
            ULP_X_RP_Capsule = 149,
            A_Point = 150,
            B_Point = 151,
            Snowflake_Forest = 152,
            Green_Dots = 153,
            Function_smoke_reduce = 154,
            DSR_1_DC_RP_Capsule = 155,
            SCAR_Heavy_Camo_RP_Capsule = 156,
            Color_Callsign = 157,
            Color_Chatting = 158,
            Gatling_gun_Gold_RP_Capsule = 159,
            AK_47_Knife_BS_RP_Capsule = 160,
            Winchester_Gold_RP_Capsule = 161,
            Knife_Master = 162,
            Blue_Thunder = 163,
            Forces_Collide = 164,
            Dual_1911s_RD_RP_Capsule = 165,
            M4A1_Bandage_RP_Capsule = 166,
            Red_Dragon_Mega_RP_Capsule = 167,
            Plus_Mission = 168,
            Badge_Plus_100 = 169,
            GP_Plus_70 = 170,
            EXP_Plus_50_2 = 171,
            Kriss_SV_LM_RP_Capsule = 172,
            MG3_Gold_RP_Capsule = 173,
            DSR_1_Rusty_RP_Capsule = 174,
            Galil_RP_Capsule = 175,
            EXP_Plus_100 = 176,
            London_2012_Summer_Games_1 = 177,
            London_2012_Summer_Games_2 = 178,
            London_2012_Summer_Games_1_2 = 179,
            London_2012_Summer_Games_2_2 = 180,
            _1_Year_Anniversary_Mega_RP_Capsule = 181,
            MP7A1_GP_Capsule = 182,
            GSG_9_RP_Capsule = 183,
            _1_Year_Anniversary_2 = 184,
            _1_Year_Anniversary_3 = 185,
            Sterling_RP_Capsule = 186,
            M37_Stakeout_Hellfire_RP_Capsule = 187,
            SCAR_Heavy_RD_RP_Capsule = 188,
            Octane_RP_Capsule = 189,
            _2012_WCG_1 = 190,
            _2012_WCG_2 = 191,
            _2012_WCG_1_2 = 192,
            _2012_WCG_2_2 = 193,
            Octane = 194,
            Octane_RP_Capsule_2 = 195,
            Autumn_Camo_RP_Capsule = 196,
            Knuckles_RP_Capsule = 197,
            _2012_Halloween_Mega_RP_Capsule = 198,
            _2012_Halloween_Mega_RP_Capsule_2 = 199,
            Fiery_Pumpkin = 200,
            Spooky_Pumpkin = 201,
            AK_47_S_RP_Capsule = 202,
            Desert_Eagle_S_RP_Capsule = 203,
            XM8_B_GP_Capsule = 204,
            RPK_Red_Eagle_RP_Capsule = 205,
            _2012_Gold_Mega_RP_Capsule = 206,
            _2012_Xmas_RP_Capsule = 207,
            _2012_Xmas = 208,
            _2012_Xmas_2 = 209,
            Tree_Xmas = 210,
            F_Protection_Goggle_GHOST_X = 211,
            Biohazard_Backpack_Exchange_Ticket_Functional = 212,
            Biohazard_Acquisition_Ticket = 213,
            Biohazard_Acquisition_Ticket_2 = 214,
            Biohazard_Acquisition_Ticket_3 = 215,
            Biohazard_Acquisition_Ticket_4 = 216,
            Mega_Warmonger_box = 217,
            Mega_Warmonger = 218,
            Mega_Warmonger_2 = 219,
            Purple_Muzzle_Color = 220,
            Sitting_Behind_BL_Fire = 221,
            Sitting_Behind_GR_Fire = 222,
            _2013_New_Year_RP_Capsule = 223,
            Thompson_Gold_RP_Capsule = 224,
            M4A1_A_Crystal_RP_Capsule = 225,
        }
        public enum Bags : ushort
        {
            Bag1 = 1,
            Bag2,
            Bag3,
            Bag4,
            Bag5,
            Bag6,
            Bag7,
        }
        public enum CharacterEquipment : ushort
        {
            SWAT_Basic_Helmet = 1,
            SWAT_Basic_Face = 2,
            OMOH_Basic_Helmet = 3,
            OMOH_Basic_Face = 4,
            SAS_Basic_gas_mask = 5,
            SAS_Basic_Face = 6,
            SWAT_Basic_Pouch = 7,
            OMOH_Basic_Pouch = 8,
            SAS_Basic_Pouch = 9,
            Mutant_Helmet__Slug = 10,
            Mutant_Helmet__Mutant_hulk = 11,
            Mutant_Helmet__Crazy_Mutant = 12,
            ULP_Basic_Hair = 14,
            ULP_Basic_Face = 15,
            Tac_Helmet_A = 16,
            Leather_Goggles = 17,
            Radio_Backpack = 18,
            Compass = 19,
            Soldiers_Beret = 20,
            Officer_Beret = 21,
            Flash_Goggles = 22,
            Water_bottle_10 = 23,
            SMG_Magazine = 24,
            Rifle_Magazine = 25,
            Sniper_Magazine = 26,
            MG_Magazine = 27,
            Shotgun_Magazine = 28,
            Pistol_Magazine = 29,
            Smoke_Protection_Helmet = 30,
            Hero_default_Face = 31,
            Hero_default_Helmet = 32,
            Hero_default_BackGun = 33,
            Hero_default_GunMag = 34,
            Wicked_Pumpkin_Mask = 35,
            Pumpkin_Backpack = 36,
            Happy_Snowman_Mask = 37,
            Snowman_Backpack = 38,
            Santas_Hat = 39,
            Santas_Sack = 40,
            Sleigh_Backpack = 41,
            Rudolph_Glasses = 42,
            Baseball_Cap = 43,
            Baseball_Helmet = 44,
            Soccer_Ball_Cap = 45,
            Football_Hat = 46,
            Football_Helmet = 47,
            Fox_Hawl_Default_Helmet = 48,
            Fox_Hawl_Default_Face = 49,
            Ghost_X_F_Default_Face = 50,
            Chaos_Goggles = 51,
            Chaos_Wings = 52,
            Ghost_X_M_Default_Face = 53,
            H_C_Beanie = 54,
            H_C_Canteen = 55,
            MOS_Default_Hair = 56,
            MOS_Default_Face = 57,
            MOS_Default_Sunglass = 58,
            Tac_Helmet_A_Adv_ = 59,
            Green_Goggles_Adv_ = 60,
            Compass_Adv_ = 61,
            Radio_Backpack_Adv_ = 62,
            ULP_X_Default_Helmet = 63,
            ULP_X_Default_Face = 64,
            ULP_X_Default_Waist = 65,
            ULP_X_Default_Leg_Pouch = 66,
            Tac_Helmet_Camo = 67,
            Leather_Goggles_Adv_ = 68,
            Officer_Radio_Backpack = 69,
            Walkie_Talkie = 70,
            Rabbit_Headband = 71,
            Rabbit_Backpack = 72,
            Rabbit_Hat = 73,
            Digicam_Ballistic_Helmet = 74,
            Digicam_Canteen = 75,
            Digicam_Protective_Goggles = 76,
            Digicam_Backpack = 77,
            HumanBoss_Face = 78,
            HumanBoss_Hair = 79,
            HumanBoss_Pouch = 80,
            Skull_Beanie = 81,
            Fire_Shades = 82,
            GSG_9_Default_Helmet = 83,
            GSG_9_Default_Face = 84,
            Cake_Hat = 85,
            Wicked_Pumpkin_Mask_2 = 86,
            Pumpkin_Backpack_2 = 87,
            Devil_Wings = 88,
            Panda_Hat = 89,
            Panda_Backpack = 90,
            Panda_Water_Bottle = 91,
            Xmas_Sad_Snowman_Mask = 92,
            Ghost_X_F_Default_Face_2 = 93,
            Mega_Warmonger_Mask = 94,
            Mega_Warmonger_BackPack = 95,
            Gold_Mask = 96,
            HumanBossLady_Face = 97,
        }
        public enum Characters : ushort
        {
            SWAT = 1,
            OMOH,
            SAS,
            ULP,
            HERO,
            Fox_Howl,
            Ghost_X_F,
            Ghost_X_M,
            MOS,
            ULP_X,
            HumanBoss,
            GSG_9,
            GHOST_X,
            Ranger,
        }
        public enum WeaponIDs : ushort
        {
            AK_47 = 1,
            AK_74 = 2,
            M4A1 = 3,
            Steyr_AUG_A1 = 4,
            M16 = 5,
            K_2 = 6,
            MP5 = 7,
            Mini_Uzi = 8,
            M700 = 9,
            AWM = 10,
            M60 = 11,
            XM1014 = 12,
            Beretta_M9 = 13,
            P228 = 14,
            GRENADE = 15,
            Smoke_Grenade = 16,
            KNIFE = 17,
            FAMAS = 18,
            SCAR_Heavy = 19,
            SG552 = 20,
            Winchester = 21,
            XM8 = 22,
            QBZ95 = 23,
            MP7 = 24,
            K1A = 25,
            P90 = 26,
            DRAGUNOV = 27,
            RPK = 28,
            SPAS_12 = 29,
            Desert_Eagle = 30,
            COLT1911 = 31,
            GLOCK_18 = 32,
            Red_Smoke = 33,
            SCAR_LIGHT = 34,
            G36K = 35,
            Type89 = 36,
            AK_47_Knife = 37,
            M4A1_A = 38,
            AKS_74U = 39,
            Micro_GALIL = 40,
            MP5_A = 41,
            Dual_Uzis = 42,
            Kriss_Super_V = 43,
            AWM_A = 44,
            M60_A = 45,
            Gatling_Gun = 46,
            Dual_Desperado = 47,
            Anaconda = 48,
            Dual_1911s = 49,
            Desert_Eagle_B = 50,
            FLASHBANG = 51,
            FC_GRENADE = 52,
            Field_Shovel = 53,
            Katana = 54,
            BC_Axe = 55,
            Desert_Eagle_B_2 = 56,
            MP5_A_2 = 57,
            AWM_A_2 = 58,
            SG552_A_2 = 59,
            Red_Smoke_2 = 60,
            AK_47_2 = 61,
            AK_47_Knife_2 = 62,
            M4A1_A_2 = 63,
            M4A1_2 = 64,
            AKS_74U_2 = 65,
            MP5_A_3 = 66,
            Dual_Uzis_2 = 67,
            AWM_2 = 68,
            AWM_A_3 = 69,
            M60_2 = 70,
            M60_A_2 = 71,
            Gatling_Gun_2 = 72,
            Dual_1911s_2 = 73,
            Desert_Eagle_2 = 74,
            Desert_Eagle_B_3 = 75,
            Field_Shovel_2 = 76,
            Katana_2 = 77,
            BC_Axe_2 = 78,
            Mauser_M1896 = 79,
            Dual_Barrel = 80,
            FN_M249_MINIMI = 81,
            D_EagleB = 82,
            D_Eagle_Tiger = 83,
            M4A1_A_Bronze = 84,
            Dual_BarrelB = 85,
            M4A1_A_Tiger = 86,
            Kriss_SV_Tiger = 87,
            Dual_Uzi_Tiger = 88,
            AK_47_Knife_RD = 89,
            M4A1_A_RD = 90,
            AWM_RD = 91,
            Ruger_MINI_14 = 92,
            SR_2M_Veresk = 93,
            SL8 = 94,
            Smoke_Grenade_2 = 95,
            Mini_Uzi_2 = 96,
            COLT1911_2 = 97,
            SCAR_LIGHT_2 = 98,
            Anaconda_2 = 99,
            GRENADE_2 = 100,
            XM8_2 = 101,
            DRAGUNOV_2 = 102,
            FLASHBANG_2 = 103,
            Doll_Grenade = 104,
            AWM_Stripes = 105,
            M4A1_Stripes = 106,
            D_E__Stripes = 107,
            Knife_Stripes = 108,
            M60_WCG = 109,
            MP5_WCG = 110,
            P90_WCG = 111,
            M4A1_WCG = 112,
            AK_47_WCG = 113,
            AUG_A1_WCG = 114,
            SG552_WCG = 115,
            AWM_WCG = 116,
            XM1014_WCG = 117,
            COLT1911_WCG = 118,
            Desert_Eagle_WCG = 119,
            KNIFE_WCG = 120,
            GRENADE_WCG = 121,
            FLASHBANG_WCG = 122,
            SMOKE_WCG = 123,
            B_C_Axe_WCG = 124,
            Ghost_G = 125,
            M4A1_H = 126,
            Jack_Hammer_H = 127,
            Field_Shovel_H = 128,
            Pumpkin_G = 129,
            Rose_Grenade = 130,
            AK_47_Knife_RD_2 = 131,
            Keris_Xmas = 132,
            AWM_Xmas = 133,
            Kriss_SV_Xmas = 134,
            M4A1_Xmas = 135,
            Snowflake_Grenade = 136,
            M249_Xmas = 137,
            Glock_18_Xmas = 138,
            DSR_1 = 139,
            TAR21 = 140,
            Nano_Grenade = 141,
            Soccer_Grenade = 142,
            FN_F2000 = 143,
            M249_Gold = 144,
            Dual_D_E = 145,
            AK47_Gold = 146,
            XM8_A = 147,
            TAR21_2 = 148,
            DSR_1_2 = 149,
            Lotus_Grenade = 150,
            P90_Camo = 151,
            Winchester_S = 152,
            M12s = 153,
            MP7_2 = 154,
            Keris = 155,
            Micro_Galil_S = 156,
            Chaos_Hook = 157,
            Mace_Grenade = 158,
            USP = 159,
            Anaconda_3 = 160,
            PSG_1 = 161,
            PSG_1_S = 162,
            MSG90 = 163,
            Beretta_AR_70 = 164,
            Thompson = 165,
            M14EBR = 166,
            RPK_Gold = 167,
            PP_19_Bizon = 168,
            XM1014_A = 169,
            FAMAS_CAMO = 170,
            AWM_Pink = 171,
            Dual_Uzi_Pink = 172,
            M4A1_Pink = 173,
            MP7_Pink = 174,
            M4A1_Custom = 175,
            M37_stakeout = 176,
            QBZ95_A = 177,
            Steyr_Aug_A1_A = 178,
            Beretta_AR_70_2 = 179,
            Bushmaster_ACR_2 = 180,
            Micro_Galil_S_2 = 181,
            Thompson_2 = 182,
            Dual_Barrel_2 = 183,
            Ultimax_100 = 184,
            PSG_1_2 = 185,
            Mauser_M1896_2 = 186,
            Kukri = 187,
            DSR_1_DC = 188,
            SCAR_Heavy_Camo = 189,
            RX4_Storm = 190,
            M16A3_LMG = 191,
            MP7_A = 192,
            USP_2 = 193,
            EasterEgg_G = 194,
            XM8_Jasmine = 195,
            Gatling_gun_Gold = 196,
            AK_47_Knife_BS = 197,
            Winchester_Gold = 198,
            Beretta_M93R = 199,
            M16A2 = 200,
            MSG90_2 = 201,
            Dual_1911s_RD = 202,
            M4A1_Bandage = 203,
            Field_shovel_RD = 204,
            SCAR_LIGHT_RD = 205,
            Anaconda_RD = 206,
            SG552_B = 207,
            L85A1 = 208,
            AK_47_B = 209,
            QBZ03 = 210,
            Kriss_SV_LM = 211,
            MG3_Gold = 212,
            DSR_1_Rusty = 213,
            Galil = 214,
            Jack_Hammer = 215,
            Ruger_Bisley = 216,
            M16_A = 217,
            M4A1_Royal_Dragon = 218,
            Kukri_Royal_Dragon = 219,
            MP7A1 = 220,
            KTR_08 = 221,
            FC_GRENADE_2 = 222,
            Sterling = 223,
            M37_Stakeout_Hellfire = 224,
            SCAR_Heavy_RD = 225,
            Jack_Hammer_Octane = 226,
            M4A1_Custom_Octane = 227,
            BC_Axe_Octane = 228,
            MK23_Octane = 229,
            Jack_Hammer_Octane_2 = 230,
            M4A1_Custom_Octane_2 = 231,
            BC_Axe_Octane_2 = 232,
            MK23_Octane_2 = 233,
            Octane_Grenade = 234,
            M60_2012_WCG = 235,
            MP5_2012_WCG = 236,
            P90_2012_WCG = 237,
            M4A1_2012_WCG = 238,
            AK47_2012_WCG = 239,
            Steyr_AUG_A1_2012_WCG = 240,
            SG552_2012_WCG = 241,
            AWM_2012_WCG = 242,
            XM1014_2012_WCG = 243,
            COLT1911_2012_WCG = 244,
            Desert_Eagle_2012_WCG = 245,
            Knife_2012_WCG = 246,
            GRENADE_2012_WCG = 247,
            FLASHBANG_2012_WCG = 248,
            SMOKE_2012_WCG = 249,
            BC_AXE_2012_WCG = 250,
            LR300ML = 251,
            D_Eagle_Crystal = 252,
            AWM_Blue_Diamond = 253,
            M4A1_Custom_Autumn_Camo = 254,
            BC_Axe_Autumn_Camo = 255,
            M4A1_Custom_Autumn_Camo_2 = 256,
            BC_Axe_Autumn_Camo_2 = 257,
            Autumn_Camo_Grenade = 258,
            Knuckles = 259,
            Kriss_Super_V_H = 260,
            Mauser_M1896_H = 261,
            Gatling_gun_H = 262,
            FR_F2_H = 263,
            M4A1_X_H = 264,
            M16_S_Camo = 265,
            AK_47_S = 266,
            Desert_Eagle_S = 267,
            XM8_B = 268,
            RPK_Red_Eagle = 269,
            Dual_Double_Barrel_Silver = 270,
            SCAR_Light_Gold = 271,
            Anaconda_Gold = 272,
            AWM_A_XMas = 273,
            M14EBR_Xmas = 274,
            AK47_Xmas = 275,
            BC_Axe_Xmas = 276,
            M14EBR_Ultimate_Gold = 277,
            AR_57 = 278,
            FN_F2000_Green_Skull = 279,
            Dual_D_E_Green_Vein = 280,
            Biohazard_Mode_Grenade = 281,
            Mega_Warmonger_Fists = 282,
            MG3_Perfect_Silver = 283,
            M1216 = 284,
            SW_M66 = 285,
            Ghost_Grenade = 286,
            M37_Stakeout = 287,
            Nano_Grenade_2 = 288,
            Barrett_M82A1_Red_Dragon = 289,
            Steyr_Aug_A1_Red_Dragon = 290,
            Anaconda_RD_2 = 291,
            Thompson_Gold = 292,
            M4A1_A_Crystal = 293,
            M60E3 = 294,
            Machete = 295,
            TRG_21 = 296
        }
        public enum WeaponTypes : byte
        {
            SHOTGUN = 0,
            SMG = 1,
            RIFLE = 2,
            SNIPER_RIFLE = 3,
            MG = 4,
            PISTOL = 5,
            KNIFE = 6,
            GRENADE = 7
        }
    }
}
